version: v1beta1
name: profile-retail-product
type: workflow
tags:
- merchandise
- retail
- has_profile
description: The job performs profiling on top of retail product data
#owner: deenkar_rubik
workflow:
  title: Product Profiler
  dag:
  - name: ps-product
    title: Product Data Profiler
    description: The job performs profiling on Product data
    spec:
      tags:
      - merchandise
      - retail
      - has_profile
      stack: flare:1.0
      title: Product Data Profiler
      persistentVolume:
        name: persistent-v
        directory: fides
      flare:
        driver:
          coreLimit: 1200m
          cores: 1
          memory: 1000m
        executor:
          coreLimit: 1200m
          cores: 1
          instances: 2
          memory: 1000m
        job:
          # ignore steps & outputs
          explain: true
          inputs:
            - name: product_input
              dataset: dataos://icebase:merchandise_retail/retail_product
              format: iceberg
          logLevel: WARN
          profile:
            # basic | intermediate | advanced
            level: basic
            #filters:
            #  - type: expression
            #    expression: "gender='MALE'"

        sparkConf:
        - spark.sql.shuffle.partitions: 10
        - spark.default.parallelism: 10